<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Worms.Server</AssemblyName>
    <RootNamespace>Worms.Server</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../shared/Protocol/Protocol.csproj" />
  </ItemGroup>
</Project>
